### GET repos
GET http://localhost:8080/repos

### CREATE a repo
POST http://localhost:8080/repos

{
   "name": "aaaaaa",
   "description": "code, but bad"
}

### GET a single repo
GET http://localhost:8080/repo/aaaaaa.git

### UPDATE a repo
PUT http://localhost:8080/repo/aaaaaa.git

### DELETE a repo
DELETE http://localhost:8080/repo/aaaaaa.git

