services:
  gitserver:
    image: gitserver
    build:
      dockerfile: Dockerfile.server
    volumes:
      - ./repos:/srv/git
    ports:
      - 9418:9418
  gitweb:
    image: rockstorm/gitweb
    volumes:
      - ./repos:/srv/git
    ports:
      - 8081:80
  gitapi:
    image: gitapi
    build:
      dockerfile: Dockerfile.api
    volumes:
      - ./repos:/srv/git
    ports:
      - 8080:80
