services:
  gitserver:
    image: gitserver
    build:
      dockerfile: Dockerfile.gitserver
    volumes:
      - ./repos:/srv/git
    ports:
      - 9418:9418
  gitweb:
    image: rockstorm/gitweb
    volumes:
      - ./repos:/srv/git
    ports:
      - 8081:80
