FROM golang:1.23-alpine

EXPOSE 8080

RUN mkdir /app
WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o ./bin/gitapi ./cmd/server/main.go
CMD ["./bin/gitapi"]

