---
- name: Ensure project directory exists on the server.
  file:
    path: "{{ config_dir }}"
    state: directory

- name: Copy project root to the server (excluding unnecessary files)
  ansible.posix.synchronize:
    src: ./ 
    dest: "{{ config_dir }}/{{ project_name }}"
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=README.md"
      - "--exclude=inventory.ini"
      - "--exclude=example.inventory.ini"
      - "--exclude=.env"
      - "--exclude=repos"

- name: Ensure repos directory exists on the server.
  ansible.builtin.file:
    path: "{{ config_dir }}/{{ project_name }}/repos"
    state: directory

- name: Ensure githomestead environment is running.
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/{{ project_name }}"
    build: always
    recreate: always
    state: present
  become: false
